name: CI/CD Pipeline
#d
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v3
      